### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by fan1x** [luk27official/platform041#1]
Cannot compile under Windows WSL
Error: 
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindX11.cmake:457 (find_package_handle_standard_args)
  build/_deps/sfml-src/cmake/Macros.cmake:391 (find_package)
  build/_deps/sfml-src/src/SFML/Window/CMakeLists.txt:294 (sfml_find_package)
```

Please specify all the required libraries in the documentation, I can download if need. Or include into the script

Cmake output: [CMakeOutput.log](https://github.com/luk27official/platform041/files/10695876/CMakeOutput.log)

**Comment by luk27official** [comment]
CMake takes the SFML sources and tries to compile them. For some systems, all of the dev libraries are already included, but it seems that WSL distributions do not have them.

This command should do the job for Linux: `sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg8-dev libsndfile1-dev libopenal-dev libxcursor-dev libudev-dev libflac-dev libvorbis-dev`

I will update the docs.

**Comment by fan1x** [comment]
Regarding the documentation, it's always better to specify which non-standard (not STL) libraries you are using and which version you are expecting so the users can install them and get all the potential dependencies. Ofc, it's nice to create the script that do this for you, but you must be careful on the 3rd dependencies (i.e., dependencies of the dependencies).

**Comment by luk27official** [comment]
I was a bit surprised that WSL does not have the libraries included (because the GitHub Linux workflow compiles without problems as well).

I have found the following [SFML article](https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php#installing-dependencies) which lists all the dependencies. Hopefully this clears everything up.
