### ISSUE TITLE
Replace all unnecessary shared_ptrs with unique_ptrs

### ISSUE THREAD

**Issue by fan1x** [luk27official/platform041#4]
E.g., 
https://github.com/luk27official/platform041/blob/390bdfc46152ffae1eb9ee4a08911810b5c9d7c5/src/Level.hpp#L39

**Comment by luk27official** [comment]
In case to achieve this, I had to change some methods to use raw pointers to avoid unnecessary ownership moves, but as the ownership transfer is not needed, I think it's fine.
