### ISSUE TITLE
Status window + lose window

### ISSUE THREAD

**Issue by fan1x** [luk27official/platform041#5]
Similar as you do for winning, I would like to see this windows maybe after every failure. Also, after finishing a level? Also, can you add stats window (at the beginning, you can have a menu -> `[levels, stats]` or something like that where you can see all the overall stats with names etc...

**Comment by luk27official** [comment]
I added a lose window as you wanted, which works pretty much the same as the win window.

For the scores - I added a simple scores file. The file can be viewed via the `Scores` button from the main menu. It shows the level, score and time. I decided not to add player names - I do not think it is really beneficial in any way as the game is singleplayer only, it would require decisions like getting the name from the user etc.
