### ISSUE TITLE
Weird collision detection when jumping

### ISSUE THREAD

**Issue by fan1x** [luk27official/platform041#6]
Kdyz se priblizim co nejbliz to jde k prekazce a skocim, tak panacek zustane potom na prekazce, coz nedava moc smysl "fyzikalne". Mel by zase spadnou dolu

**Comment by luk27official** [comment]
Improved in most cases, it may happen in rare scenarios though. Would be resolvable by forcing the player to move on the sides when colliding on the sides, but I think it is more logical to leave it this way - fixing this bug would mean that the stickman is controlled by the game which I do not like.
